using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using UnityBestPractices.Analyzers;
using Xunit;

// Deliberately separate from rule correctness tests: a failure here is an analyzer-host
// stability regression, not an ordinary semantic false-positive/false-negative.
public sealed class HostRobustnessTests
{
    public static IEnumerable<object[]> HostileSources()
    {
        yield return new object[] { "incomplete-declarations", "class C { MissingType field; void M(" };
        yield return new object[] { "missing-references", "class C { System.Xml.XmlDocument M() => null; }" };
        yield return new object[] { "unresolved-unity-types", "class C : UnityEngine.MonoBehaviour { Unity.Collections.NativeArray<int> values; void M() { UnityEngine.Camera.main.ToString(); } }" };
        yield return new object[] { "ambiguous-symbols", "using A; using B; namespace A { class Item {} } namespace B { class Item {} } class C { Item value; }" };
        yield return new object[] { "syntax-errors-around-candidate", "class C { void M() { var x = new Missing(,); x.Call(; yield return 0; } }" };
    }

    [Theory]
    [MemberData(nameof(HostileSources))]
    public async Task AnalyzerCallbacksDoNotEscapeExceptions(string caseName, string source)
    {
        await AnalyzerHostHarness.AssertStableAsync(caseName, new[] { ("Candidate.cs", source) });
    }

    [Fact]
    public async Task GeneratedCodeIsIgnoredAndStable()
    {
        var diagnostics = await AnalyzerHostHarness.AssertStableAsync(
            "generated-code",
            new[] { ("Candidate.g.cs", "// <auto-generated/>\nclass C { void M() { yield return 0; } }") });

        Assert.Empty(diagnostics);
    }

    [Fact]
    public async Task LinkedDocumentsAreStable()
    {
        using var workspace = new AdhocWorkspace();
        var solution = workspace.CurrentSolution;
        var sharedPath = "/shared/Linked.cs";
        foreach (var name in new[] { "First", "Second" })
        {
            var projectId = ProjectId.CreateNewId(name);
            solution = solution.AddProject(projectId, name, name, LanguageNames.CSharp)
                .WithProjectCompilationOptions(projectId, new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
                .AddMetadataReference(projectId, MetadataReference.CreateFromFile(typeof(object).Assembly.Location))
                .AddDocument(DocumentId.CreateNewId(projectId), "Linked.cs", SourceText.From("class C { Missing M() => new Missing(); }"), filePath: sharedPath);
        }

        foreach (var project in solution.Projects)
        {
            await AnalyzerHostHarness.AssertStableAsync("linked-documents/" + project.Name, project);
        }
    }

    [Fact]
    public async Task CatalogHasMissingSymbolAndMalformedCodeCoverage()
    {
        var cases = new[]
        {
            (Name: "missing-symbol", Source: "class C { MissingType field; void M() { MissingApi.Call(); } }"),
            (Name: "malformed-code", Source: "class C { void M( { var value = new Missing(,); }"),
        };

        foreach (var rule in DiagnosticCatalog.All)
        foreach (var sourceCase in cases)
        {
            // Include the rule ID in the harness label so AD0001 failures identify both
            // the responsible diagnostic and exact catalog/source matrix cell.
            await AnalyzerHostHarness.AssertStableAsync(
                $"{rule.DiagnosticId}/{sourceCase.Name}",
                new[] { (rule.DiagnosticId + ".cs", sourceCase.Source) });
        }
    }

    [Fact]
    public async Task AnalyzerExecutionHonorsCancellation()
    {
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        var compilation = AnalyzerHostHarness.CreateCompilation("class C { void M() { } }");
        var driver = compilation.WithAnalyzers(ImmutableArray.Create<DiagnosticAnalyzer>(new UnityBestPracticesAnalyzer()));

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => driver.GetAnalyzerDiagnosticsAsync(cancellation.Token));
    }

    [Fact]
    public async Task CodeFixRegistrationHonorsCancellation()
    {
        var document = AnalyzerHostHarness.CreateDocument("class C { void M() { } }");
        var diagnostic = Diagnostic.Create(DiagnosticCatalog.Get(DiagnosticIds.YieldNull).Descriptor, Location.Create((await document.GetSyntaxTreeAsync())!, new TextSpan(0, 1)));
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => new UnityBestPracticesCodeFixProvider().RegisterCodeFixesAsync(
            new CodeFixContext(document, diagnostic, (_, _) => { }, cancellation.Token)));
    }

    [Fact]
    public async Task CodeFixApplicationHonorsCancellation()
    {
        var (document, diagnostic, action) = await GetYieldNullFixAsync();
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        _ = document;
        _ = diagnostic;

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => action.GetOperationsAsync(cancellation.Token));
    }

    [Fact]
    public async Task FixAllApplicationHonorsCancellation()
    {
        var (document, diagnostic, _) = await GetYieldNullFixAsync();
        var provider = new UnityBestPracticesCodeFixProvider();
        var context = new FixAllContext(
            document,
            provider,
            FixAllScope.Document,
            DiagnosticIds.YieldNull,
            new[] { DiagnosticIds.YieldNull },
            new SingleDiagnosticProvider(diagnostic),
            CancellationToken.None);
        var action = await provider.GetFixAllProvider().GetFixAsync(context);
        Assert.NotNull(action);
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => action!.GetOperationsAsync(cancellation.Token));
    }

    [Fact]
    public async Task SemanticPreconditionsAreRevalidatedBeforeRegistration()
    {
        var document = AnalyzerHostHarness.CreateDocument("class C { void M() { int value = 0; } }");
        var tree = await document.GetSyntaxTreeAsync();
        var staleDiagnostic = Diagnostic.Create(
            DiagnosticCatalog.Get(DiagnosticIds.EncapsulateSerializedField).Descriptor,
            Location.Create(tree!, new TextSpan(0, 1)),
            "value");
        var actions = new List<CodeAction>();

        await new UnityBestPracticesCodeFixProvider().RegisterCodeFixesAsync(
            new CodeFixContext(document, staleDiagnostic, (action, _) => actions.Add(action), CancellationToken.None));

        Assert.Empty(actions);
    }

    [Fact]
    public async Task TransformPreservesCompilationOtherDocumentsAndTrivia()
    {
        var document = AnalyzerHostHarness.CreateDocument("class C : UnityEngine.MonoBehaviour { System.Collections.IEnumerator M() { /* meaningful */ yield return 0; } }");
        var other = document.Project.AddDocument("Unrelated.cs", SourceText.From("// untouched\nclass Unrelated { }"));
        document = other.Project.GetDocument(document.Id)!;
        var (_, _, action) = await GetYieldNullFixAsync(document);
        var beforeOther = (await other.GetTextAsync()).ToString();
        var operations = await action.GetOperationsAsync(CancellationToken.None);
        var changed = Assert.IsType<ApplyChangesOperation>(Assert.Single(operations)).ChangedSolution;
        var changedDocument = changed.GetDocument(document.Id)!;

        Assert.Equal(beforeOther, (await changed.GetDocument(other.Id)!.GetTextAsync()).ToString());
        Assert.Contains("/* meaningful */", (await changedDocument.GetTextAsync()).ToString(), StringComparison.Ordinal);
        var compilerErrors = (await changedDocument.Project.GetCompilationAsync())!.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error);
        Assert.Empty(compilerErrors);
    }

    private static async Task<(Document Document, Diagnostic Diagnostic, CodeAction Action)> GetYieldNullFixAsync(
        string source = "class C : UnityEngine.MonoBehaviour { System.Collections.IEnumerator M() { yield return 0; } }")
        => await GetYieldNullFixAsync(AnalyzerHostHarness.CreateDocument(source));

    private static async Task<(Document Document, Diagnostic Diagnostic, CodeAction Action)> GetYieldNullFixAsync(
        Document document)
    {
        var compilation = (await document.Project.GetCompilationAsync())!;
        var diagnostics = await compilation.WithAnalyzers(ImmutableArray.Create<DiagnosticAnalyzer>(new UnityBestPracticesAnalyzer())).GetAnalyzerDiagnosticsAsync();
        var diagnostic = diagnostics.SingleOrDefault(d => d.Id == DiagnosticIds.YieldNull);
        Assert.True(
            diagnostic is not null,
            string.Join(Environment.NewLine, compilation.GetDiagnostics().Select(item => item.ToString())));
        var actions = new List<CodeAction>();
        await new UnityBestPracticesCodeFixProvider().RegisterCodeFixesAsync(
            new CodeFixContext(document, diagnostic!, (action, _) => actions.Add(action), CancellationToken.None));
        return (document, diagnostic!, Assert.Single(actions));
    }

    private sealed class SingleDiagnosticProvider : FixAllContext.DiagnosticProvider
    {
        private readonly Diagnostic _diagnostic;

        internal SingleDiagnosticProvider(Diagnostic diagnostic) => _diagnostic = diagnostic;

        public override Task<IEnumerable<Diagnostic>> GetDocumentDiagnosticsAsync(
            Document document,
            CancellationToken cancellationToken) =>
            Task.FromResult<IEnumerable<Diagnostic>>(new[] { _diagnostic });

        public override Task<IEnumerable<Diagnostic>> GetProjectDiagnosticsAsync(
            Project project,
            CancellationToken cancellationToken) =>
            Task.FromResult<IEnumerable<Diagnostic>>(Array.Empty<Diagnostic>());

        public override Task<IEnumerable<Diagnostic>> GetAllDiagnosticsAsync(
            Project project,
            CancellationToken cancellationToken) =>
            Task.FromResult<IEnumerable<Diagnostic>>(new[] { _diagnostic });
    }
}

internal static class AnalyzerHostHarness
{
    internal static CSharpCompilation CreateCompilation(string source) => CSharpCompilation.Create(
        "Robustness",
        new[] { CSharpSyntaxTree.ParseText(source) },
        new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
        new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

    internal static Document CreateDocument(string source)
    {
        var workspace = new AdhocWorkspace();
        var project = workspace.AddProject("Robustness", LanguageNames.CSharp)
            .WithCompilationOptions(new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddMetadataReference(MetadataReference.CreateFromFile(typeof(object).Assembly.Location));
        return project.AddDocument(
            "Candidate.cs",
            SourceText.From(TestSources.UnityEngine + Environment.NewLine + source));
    }

    internal static async Task<ImmutableArray<Diagnostic>> AssertStableAsync(
        string caseName,
        IEnumerable<(string Name, string Source)> documents)
    {
        var compilation = CSharpCompilation.Create(
            "Robustness_" + caseName.Replace('/', '_'),
            documents.Select(d => CSharpSyntaxTree.ParseText(d.Source, path: d.Name)),
            new[] { MetadataReference.CreateFromFile(typeof(object).Assembly.Location) },
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        return await AssertStableAsync(caseName, compilation);
    }

    internal static async Task<ImmutableArray<Diagnostic>> AssertStableAsync(string caseName, Project project) =>
        await AssertStableAsync(caseName, (await project.GetCompilationAsync())!);

    private static async Task<ImmutableArray<Diagnostic>> AssertStableAsync(string caseName, Compilation compilation)
    {
        var exceptions = new List<string>();
        var options = new CompilationWithAnalyzersOptions(
            new AnalyzerOptions(ImmutableArray<AdditionalText>.Empty),
            (exception, analyzer, diagnostic) => exceptions.Add($"{caseName}: {diagnostic.Id} ({analyzer.GetType().Name}): {exception}"),
            concurrentAnalysis: true,
            logAnalyzerExecutionTime: false);
        var diagnostics = await compilation.WithAnalyzers(
            ImmutableArray.Create<DiagnosticAnalyzer>(new UnityBestPracticesAnalyzer()), options).GetAnalyzerDiagnosticsAsync();
        var driverFailures = diagnostics.Where(d => d.Id == "AD0001").Select(d => $"{caseName}: {d}");
        Assert.True(exceptions.Count == 0 && !driverFailures.Any(), string.Join(Environment.NewLine, exceptions.Concat(driverFailures)));
        return diagnostics;
    }
}
